product: 1.0.0

info:
  name: Muen Hoodie Design
  title: Muen Hoodie Design
  version: 1.0.0
  description: Creating a hoodie pattern design, which is a visual expression of an idea or intention, has been a process for us because A cozy hoodie pattern design is a wardrobe must-have – both casual and stylish. We preferred to make this hoodie model by adding stripes and animal figures.Please contact us and get one step closer to your dream design
  contact: 
    name: BurakOzcan
    url: 'https://www.behance.net/'
    email: burrakkozcaan@gmail.com
  license:
    name: MIT License
    url: 'http://www.muen.cf/license'
  termsOfService: This service is an design and sell only

visibility:
   view:
      enabled: true
      type: public
   subscribe:
      enabled: true
      type: authenticated
